---
kind: pipeline
type: docker
name: Production pipeline

steps:
  - name: publish image to production
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_production
      secret_key:
        from_secret: aws_access_key_secret_production
      region: eu-west-1
      repo: cust-production-newsletter-ecr/nyhedsbreveprofiladmin
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - latest
        - ${CI_COMMIT_SHA}

  - name: Deploy to production
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_ID:
        from_secret: bpc_app_id_prod
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_prod
      settings:
        secret_environment_variables:
          - BPC_APP_ID
          - BPC_APP_SECRET
        environment_variables:
          - MDBAPI_ADDRESS=10.94.8.199
          - MDBAPI_PORT=8000
          - BPC_URL=https://bpc.berlingskemedia.net
      aws_access_key_id:
        from_secret: aws_access_key_production
      aws_secret_access_key:
        from_secret: aws_access_key_secret_production
      cluster: cust-production-node
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-production-newsletter-ecr/nyhedsbreveprofiladmin
      container_name: cust-production-newsletter-nyhedsbreveprofiladmin-container
      family: cust-production-newsletter-nyhedsbreveprofiladmin
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-prodction-node
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=cust-prodction-newsletter-nyhedsbreveprofiladmin
      memory: 512
      port_mappings:
        - 8000 8000
      region: eu-west-1
      service: cust-production-newsletter-nyhedsbreveprofiladmin
      service_network_security_groups:
      [security_groups]
      service_network_subnets:
      [subnets]
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-production-newsletter-nyhedsbreveprofiladmin-exec
      task_memory: 512
      task_network_mode: awsvpc

trigger:
  repo:
    - BerlingskeMedia/nyhedsbreveprofiladmin
  branch:
    - master
  event:
    include:
      - push
    exclude:
      - pull_request

---
kind: pipeline
type: docker
name: test pipeline

steps:
  - name: publish image to test
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      region: eu-west-1
      repo: cust-testing-newsletter-ecr/nyhedsbreveprofiladmin
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - ${DRONE_TAG}-${CI_COMMIT_SHA}
        - ${CI_COMMIT_SHA}

  - name: Deploy to test QA1
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_ID:
        from_secret: bpc_app_id_test
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_test
    settings:
      secret_environment_variables:
        - BPC_APP_ID
        - BPC_APP_SECRET
      environment_variables:
        - MDBAPI_ADDRESS=10.94.93.46
        - MDBAPI_PORT=8000
        - BPC_URL=https://bpc.berlingskemedia-testing.net
      aws_access_key_id:
        from_secret: aws_access_key_testing
      aws_secret_access_key:
        from_secret: aws_access_key_secret_testing
      cluster: cust-testing-node
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-testing-newsletter-ecr/nyhedsbreveprofiladmin
      container_name: cust-testing-newsletter-nyhedsbreveprofiladmin-container
      family: cust-testing-newsletter-nyhedsbreveprofiladmin
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-testing-node
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=cust-testing-newsletter-nyhedsbreveprofiladmin
      memory: 512
      port_mappings:
        - 8000 8000
      region: eu-west-1
      service: cust-testing-newsletter-nyhedsbreveprofiladmin
      service_network_security_groups:
        [security_groups]
      service_network_subnets:
        [subnets]
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-nyhedsbreveprofiladmin-exec
      task_memory: 512
      task_network_mode: awsvpc
    when:
      ref:
        include:
          - refs/tags/qa1*
        exclude:
          - refs/heads/master

trigger:
  repo:
    - BerlingskeMedia/nyhedsbreveprofiladmin
  event:
    - tag
  ref:
    include:
      - refs/tags/qa*
---
kind: "secret"
name: "aws_access_key_testing"
get:
  path: "drone/cust-testing-newletter"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_testing"
get:
  path: "drone/cust-testing-newletter"
  name: "aws_access_key_secret"
---
kind: "secret"
name: "aws_access_key_production"
get:
  path: "drone/cust-production-newletter"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_production"
get:
  path: "drone/cust-production-newletter"
  name: "aws_access_key_secret"
---
kind: "secret"
name: "my_test_ssm_secret"
get:
  path: "drone/cust-testing-newletter"
  name: "some_ssm_value_name"
