---
kind: pipeline
type: docker
name: Production pipeline

steps:
  - name: publish image to production
    image: plugins/ecr
    settings:
      mirror: https://proxy.docker.all.berlingskemedia.net
      access_key:
        from_secret: aws_access_key_prod
      secret_key:
        from_secret: aws_access_key_secret_prod
      region: eu-west-1
      repo: cust-production-newsletter-ecr/nyhedsbreveprofiladmin
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - latest
        - ${CI_COMMIT_SHA}

  - name: Deploy to production
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_ID:
        from_secret: bpc_app_id_prod
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_prod
      MDBAPI_ADDRESS:
        from_secret: mdbapi_service_discovery_prod
    settings:
      task_role_arn: arn:aws:iam::815296035528:role/cust-production-newsletter-npa-exec
      secret_environment_variables:
        - BPC_APP_ID
        - BPC_APP_SECRET
        - MDBAPI_ADDRESS
      environment_variables:
        - MDBAPI_PORT=8000
        - BPC_URL=https://bpc.berlingskemedia.net
        - LOG_LEVEL=info
      access_key:
        from_secret: aws_access_key_prod
      secret_key:
        from_secret: aws_access_key_secret_prod
      cluster: cust-production-newsletter
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-production-newsletter-ecr/nyhedsbreveprofiladmin
      container_name: cust-production-newsletter-npa-container
      family: cust-production-newsletter-npa
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-production-newsletter
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=newsletter-npa
        - awslogs-datetime-format=\[%Y-%m-%d %H:%M:%S\]
      memory: 512
      port_mappings:
        - 8000 8000
      region: eu-west-1
      service: cust-production-newsletter-npa
      service_network_security_groups:
        - sg-0c2900399db25f1d7
        - sg-07de4dcb17a9d8f2e
      service_network_subnets:
        - subnet-061a8876f7f68ea21
        - subnet-0ace4f6a68677187c
        - subnet-01633ca14c693e302
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-production-newsletter-npa-exec
      task_memory: 512
      task_network_mode: awsvpc

trigger:
  repo:
    - BerlingskeMedia/nyhedsbreveprofiladmin
  branch:
    - master
  event:
    include:
      - push
    exclude:
      - pull_request

---
kind: pipeline
type: docker
name: test pipeline

steps:
  - name: publish image to test
    image: plugins/ecr
    settings:
      mirror: https://proxy.docker.all.berlingskemedia.net
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      region: eu-west-1
      repo: cust-testing-newsletter-ecr/nyhedsbreveprofiladmin
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - ${DRONE_TAG}-${CI_COMMIT_SHA}
        - ${CI_COMMIT_SHA}

  - name: Deploy to test QA1
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_ID:
        from_secret: bpc_app_id_qa1
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_qa1
      MDBAPI_ADDRESS:
        from_secret: mdbapi_qa1_service_discovery
    settings:
      task_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-npa-qa1-exec
      secret_environment_variables:
        - BPC_APP_ID
        - BPC_APP_SECRET
        - MDBAPI_ADDRESS
      environment_variables:
        - MDBAPI_PORT=8000
        - BPC_URL=https://bpc.berlingskemedia-testing.net
        - LOG_LEVEL=debug
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      cluster: cust-testing-newsletter
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-testing-newsletter-ecr/nyhedsbreveprofiladmin
      container_name: cust-testing-newsletter-npa-qa1-container
      family: cust-testing-newsletter-npa-qa1
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-testing-newsletter
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=newsletter-npa-qa1
        - awslogs-datetime-format=\[%Y-%m-%d %H:%M:%S\]
      memory: 512
      port_mappings:
        - 8000 8000
      region: eu-west-1
      service: cust-testing-newsletter-npa-qa1
      service_network_security_groups:
        - sg-04532122919e3abd0
        - sg-0cde9b6258856237a
      service_network_subnets:
        - subnet-061a8876f7f68ea21
        - subnet-0ace4f6a68677187c
        - subnet-01633ca14c693e302
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-npa-qa1-exec
      task_memory: 512
      task_network_mode: awsvpc
    when:
      ref:
        include:
          - refs/tags/qa1*
        exclude:
          - refs/heads/master

  - name: Deploy to test QA2
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_ID:
        from_secret: bpc_app_id_qa2
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_qa2
    settings:
      task_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-npa-qa2-exec
      secret_environment_variables:
        - BPC_APP_ID
        - BPC_APP_SECRET
        - MDBAPI_ADDRESS
      environment_variables:
        - MDBAPI_PORT=8000
        - BPC_URL=https://bpc.berlingskemedia-testing.net
        - LOG_LEVEL=debug
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      cluster: cust-testing-newsletter
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-testing-newsletter-ecr/nyhedsbreveprofiladmin
      container_name: cust-testing-newsletter-npa-qa2-container
      family: cust-testing-newsletter-npa-qa2
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-testing-newsletter
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=newsletter-npa-qa2
        - awslogs-datetime-format=\[%Y-%m-%d %H:%M:%S\]
      memory: 512
      port_mappings:
        - 8000 8000
      region: eu-west-1
      service: cust-testing-newsletter-npa-qa2
      service_network_security_groups:
        - sg-04532122919e3abd0
        - sg-020dc702f90d53522
      service_network_subnets:
        - subnet-061a8876f7f68ea21
        - subnet-0ace4f6a68677187c
        - subnet-01633ca14c693e302
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-testing-newsletter-npa-qa2-exec
      task_memory: 512
      task_network_mode: awsvpc
    when:
      ref:
        include:
          - refs/tags/qa2*
        exclude:
          - refs/heads/master

trigger:
  repo:
    - BerlingskeMedia/nyhedsbreveprofiladmin
  event:
    - tag
  ref:
    include:
      - refs/tags/qa*

# Generic testing secrets
---
kind: secret
name: aws_access_key_testing
get:
  path: drone/cust-testing-newsletter
  name: aws_access_key
---
kind: secret
name: aws_access_key_secret_testing
get:
  path: drone/cust-testing-newsletter
  name: aws_access_key_secret
---
kind: secret
name: mdbapi_qa1_service_discovery
get:
  path: drone/cust-testing-newsletter
  name: mdbapi_qa1_service_discovery
---
kind: secret
name: mdbapi_qa2_service_discovery
get:
  path: drone/cust-testing-newsletter
  name: mdbapi_qa2_service_discovery

# PROD secrets
---
kind: secret
name: aws_access_key_prod
get:
  path: drone/cust-production-newsletter
  name: aws_access_key
---
kind: secret
name: aws_access_key_secret_prod
get:
  path: drone/cust-production-newsletter
  name: aws_access_key_secret
---
kind: secret
name: mdbapi_service_discovery_prod
get:
  path: drone/cust-production-newsletter
  name: mdbapi_service_discovery
